### ISSUE TITLE
Looking for iTerm2 and Atom templates

### ISSUE THREAD

**Issue by thibaudgg** [chriskempson/base16-templates-source#21]
Hi,

I'm looking for iTerm2 and Atom builder templates. They were present in the deprecated [base16-builder repo](https://github.com/chriskempson/base16-builder/tree/master/templates), but they seem to be missing from the [yaml list](https://github.com/chriskempson/base16-templates-source/blob/master/list.yaml) here. 

Any reason why they've not been migrated yet? 

Thanks for your work!

**Comment by chriskempson** [comment]
I was the creator/maintainer of the iTerm2 template but as I no longer have access to a Mac I can't really continue that role so I'm looking for someone to take it over. As for Atom, I didn't create that so it could be that the maintainer has not yet ported it to the new system or no longer wishes to maintain it.

**Comment by thibaudgg** [comment]
Ok, thanks for the update Chris.
